apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-webapp-nodejs
  name: simple-webapp-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webapp-nodejs
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-webapp-nodejs
    spec:
      containers:
      - image: gehadgkamel/simple-webapp-nodejs:latest
        name: simple-webapp-nodejs
        env:
          - name: DB_HOST
            value: "postgres"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_DATABASE
            value: "postgres_db"
          - name: DB_PORT
            value: "5432"
status: {}
