apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-webapp-nodejs
  template:
    metadata:
      labels:
        app: simple-webapp-nodejs
    spec:
      containers:
      - name: simple-webapp-nodejs
        image: gehadgkamel/simple-webapp-nodejs:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres"  
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "password" 
        - name: DB_DATABASE
          value: "postgres_db"
        - name: DB_PORT
          value: "5432"